### ISSUE TITLE
Can you modify the thickness of the donut percentage?

### ISSUE THREAD

**Issue by peqp1988** [sultantarimo/cssCharts.js#7]
is there any way to play with thickness of the percentage line?

**Comment by thysultan** [comment]
@patriciapineda  Yes,

``` css
.donut-chart:after{
    width: 74%;
    height: 74%;
}
```

will make it thicker, play with those numbers to get a preferred thickness.
